# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08\x63\x65rtdemo\"8\n\x0b\x43\x65rtRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x65rtificate\x18\x02 \x01(\t\"4\n\x0c\x43\x65rtResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x65rtificate\x18\x02 \x01(\t2]\n\x12\x43\x65rtificateService\x12G\n\x14\x45xchangeCertificates\x12\x15.certdemo.CertRequest\x1a\x16.certdemo.CertResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CERTREQUEST']._serialized_start=27
  _globals['_CERTREQUEST']._serialized_end=83
  _globals['_CERTRESPONSE']._serialized_start=85
  _globals['_CERTRESPONSE']._serialized_end=137
  _globals['_CERTIFICATESERVICE']._serialized_start=139
  _globals['_CERTIFICATESERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
